### ISSUE TITLE
Add Fudge dice

### ISSUE THREAD

**Issue by DanielBaird** [Yinfei/rpg_tools#1]
The Fudge RPG, and derived systems like FATE, use dice with three possible sides: `+`, `–` and ` ` (blank).  In practice it's a cube with two sides for each symbol.  They're read as +1, -1, and 0.

Usually you roll four together, and get a result from +4 to -4 on a steep Bell curve.

Anyway a Fudge die is generally written as `F`.  So `4dF` would roll four Fudge dice, `3dF+2` would roll three Fudge dice and add two, etc.  Mathematically speaking `𝓍dF` equals `𝓍d3 - 2𝓍`, so 4dF is equivalent to 4d3-8.

It'd be cool if dice rolling allowed F as a dice type.

**Comment by Yinfei** [comment]
Hi @DanielBaird !

The gem has been updated to be fully object oriented and I took the time to add your fudge dice. I hope you'll like it ! ;)
